### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by henry314** [leptonix/node-bitscope#1]
When installing through npm under OSX an error is generated when node-gyp is invoked:

npm install bitscope

> bitscope@0.2.3 install /Users/X/node_modules/bitscope
> node-gyp rebuild

  CXX(target) Release/obj.target/bitscope/src/bitscope.o
In file included from ../src/bitscope.cc:1:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {

Node v5.0.0
Node-Gyp v3.0.3

**Comment by leptonix** [comment]
I have upgraded to Nan version 2. Should now work for Node v5.0.0.
